### ISSUE TITLE
Framerate drop in HololensCapture app

### ISSUE THREAD

**Issue by davidcian** [microsoft/psi#232]
I am using a HoloLens 2 with the dedicated PSI capture app. After around 14-15 minutes, I always notice a framerate drop precisely (and it seems exclusively) for the encoded image stream, from a stable 30.(3) FPS to a stable 20.(3) FPS. I have a recording with diagnostic data that can be opened in PsiStudio showing clearly the framerate drop (however, I'm unable to figure out the cause looking in PsiStudio).

There are slight "organic" fluctuations in the framerate due to the hardware, but this is too clean of a change in behavior and I believe it is due to something in the software (either the capture app, the server app, or PSI itself).

**Comment by sandrist** [comment]
We haven't observed this behavior, but can try and replicate your setup to see if we can reproduce the behavior or not. A few questions:
1. Are you streaming over WiFi or USB? (Whichever it is, see if the problem is reproducible when switching to the other type of connection, in case something about the network is somehow the problem)
2. Are you using the default configuration for the HoloLens app (in terms of which streams are selected, desired framerates, etc.)? Or did you change any of those settings?
3. I assume by "diagnostic data" you are referring to the simple framerate streams? Visualizing the full [Pipeline Diagnostics](https://github.com/microsoft/psi/wiki/Diagnostics) streams (for both the server side and app side) could help shed some light on the problem. E.g., are messages being dropped at the app or the server? Or is the component simply producing fewer messages after 15 minutes for some reason?

**Comment by petergu684** [comment]
> Hi, I am also experiencing some speed issue with Wifi. I tried to connect to HoloLens with usb-c but not sure how to configure the IP. Could you provide some instruction on this?
> 
> Many Thanks!

Once you connect your HoloLens 2 to your laptop with USB cable, on your laptop, go to Windows Settings - Network & Internet - Advanced network settings - Hardware and connection properties. You might be able to find a connection called Ethernet x with description UsbNcm. Use the IP address showed under that connection works for me. Similarly, you could also use the IP address under Ethernet xxx using ipconfig. If nothing shows there, just unplug and plug in again or try a different USB port on your laptop.
