### ISSUE TITLE
Question about "FFMPEGMediaSource.cs"

### ISSUE THREAD

**Issue by HaozheQi** [microsoft/psi#258]
Hi,

I need to build the [Microsoft.Psi.Media.Windows.x64](https://github.com/microsoft/psi/tree/3ec2bb7bb6a0e446fc63332a9ef58f8e42ed8075/Sources/Media/Microsoft.Psi.Media.Windows.x64) project. From the [List of Components](https://github.com/microsoft/psi/wiki/List-of-Components#file-sources) page, it seems that `FFMPEGMediaSource` implemented in [FFMPEGMediaSource.cs](https://github.com/microsoft/psi/blob/master/Sources/Media/Shared/FFMPEGMediaSource.cs) is not supported by Windows. Then why does the [Microsoft.Psi.Media.Windows.x64.csproj](https://github.com/microsoft/psi/blob/master/Sources/Media/Microsoft.Psi.Media.Windows.x64/Microsoft.Psi.Media.Windows.x64.csproj#L35) still include this components? It will give me a lot of errors when I inlcude this component.

I am looking forward to your reply!
Thank you very much!

**Comment by sandrist** [comment]
If you haven't defined the `FFMPEGDir` environment variable on your system, then Visual Studio should be able to compile the project without error, because it will skip all the code in the `FFMPEGMediaSource.cs` due to the ```#if FFMPEG``` at the top. Is this not happening in your case? Do you have that environment variable defined for some reason?

That said, you make a good point that the code is currently confusing as written, and it isn't clear if the component would work on Windows today at all, even after pointing to a valid installation of FFMPEG. As you point out in your [other issue](https://github.com/microsoft/psi/issues/257), it definitely seems to assume a quite old version of FFMPEG that is no longer easy to obtain. We'll look into this, and might consider deprecating the component entirely (or at least the Windows version of it), if it isn't easy to update the code to work with a more current FFMPEG installation and APIs.
